# Generated by Django 6.0 on 2025-12-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0004_topic_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="blog_attachments/"
            ),
        ),
    ]
